# Generated by Django 3.0.8 on 2020-07-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_auto_20200718_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('politicle', 'Politicle'), ('environment', 'Environment'), ('technology', 'Technology'), ('culture', 'Culture'), ('design', 'Design'), ('computer_science', 'Computer Science'), ('science', 'Science'), ('travel', 'Travel'), ('health', 'Health'), ('style', 'Style'), ('opinion', 'Opinion')], default='world', max_length=50),
        ),
    ]
