# Generated by Django 3.0.8 on 2020-10-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_cart',
            field=models.IntegerField(default=1),
        ),
    ]
