# Generated by Django 3.0.8 on 2020-10-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201012_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_cart',
        ),
    ]
