# Generated by Django 3.0.8 on 2020-11-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_useraccount_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_cart',
            field=models.IntegerField(default=0),
        ),
    ]
