# Generated by Django 3.0.8 on 2020-11-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccount_user_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_cart',
        ),
    ]
